export const translations = {
    pl: {
        nav: { about: "O nas", apartments: "Apartamenty", cottages: "Domki", charter: "Czarter", port: "Port", attractions: "Atrakcje", cooperation: "Współpraca", contact: "Kontakt", rooms: "Pokoje", bookBtn: "Rezerwuj" },
        hero: { title: "Wakacje na Mazurach", subtitle: "SPRAWDŹ JAK MOŻESZ SPĘDZIĆ WYJĄTKOWE I NIEZAPOMNIANE CHWILE", apartmentsBtn: "Nasze Apartamenty", charterBtn: "Czarter Jachtów" },
        intro: { tag: "Mazury.Holiday", title: "Witaj w krainie", titleHighlight: "Wielkich Jezior", p1: "Zapraszamy do odkrycia magii Mazur z perspektywy naszych luksusowych apartamentów oraz z pokładu jachtu.", p2: "Niezależnie od tego, czy szukasz spokojnego wypoczynku w Giżycku, czy ekskluzywnego domu we Fuledzie." },
        apartments: { title: "Nasze Apartamenty", description: "Wybierz idealne miejsce na swój wypoczynek.", details: "Szczegóły", pricePrefix: "od", night: "noc", people: "osoby", items: { stranda: { title: "Apartamenty Giżycko \"Stranda\"", location: "Port Stranda, Giżycko", description: "Komfortowe apartamenty położone w sercu portu Stranda." }, kisajno: { title: "Apartamenty Giżycko \"Kisajno\"", location: "Port Neptun, Giżycko", description: "Luksus nad brzegiem jeziora Kisajno." }, fuleda: { title: "Apartamenty Fuleda", location: "Fuleda, Jezioro Dobskie", description: "Oaza spokoju z dala od zgiełku miasta." } } },
        charter: { tag: "Bez patentu", title: "Czarter Jachtu Motorowego", description: "Jacht motorowy Stillo 30 to jednostka, którą możesz prowadzić bez patentu.", model: "Stillo 30 (2020)", cabins: "3 Zamykane Kabiny", checkBtn: "Sprawdź dostępność", premiumFleet: "Flota Premium", feature1: "Bez patentu", feature2: "Rocznik 2020", feature3: "Luksusowe wyposażenie", detailsBtn: "Zobacz szczegóły" },
        stranda: { subtitle: "Luksus nad jeziorem Kisajno", description: "Apartamenty Stranda Residence to połączenie nowoczesnego designu z mazurską naturą.", building: "Budynek", apartment: "Apartament" },
        details: { about: "O apartamencie", amenities: "Udogodnienia", booking: "Rezerwacja", checkAvailability: "Sprawdź dostępność i zarezerwuj.", callBtn: "Zadzwoń", lowPrice: "Gwarancja najniższej ceny.", descriptionPart1: "Luksusowy apartament w budynku", descriptionPart2: "w kompleksie Stranda Residence.", descriptionPart3: "Zapewnia niezapomniany widok na jezioro Kisajno.", items: { view: "Widok na jezioro", ac: "Klimatyzacja", terrace: "Taras z meblami", kitchen: "Aneks kuchenny", tv: "Smart TV", wifi: "WiFi", parking: "Miejsce parkingowe", sauna: "Dostęp do sauny" } },
        footer: { brandDesc: "Jedyne i niepowtarzalne chwile na Mazurach.", navTitle: "Nawigacja", contactTitle: "Kontakt", followTitle: "Obserwuj nas", rights: "Wszelkie prawa zastrzeżone.", linksTitle: "Linki" }
    },
    en: {
        nav: { about: "About Us", apartments: "Apartments", cottages: "Cottages", charter: "Charter", port: "Port", attractions: "Attractions", cooperation: "Cooperation", contact: "Contact", rooms: "Rooms", bookBtn: "Book Now" },
        hero: { title: "Holidays in Masuria", subtitle: "CHECK HOW YOU CAN SPEND UNIQUE MOMENTS", apartmentsBtn: "Our Apartments", charterBtn: "Yacht Charter" },
        intro: { tag: "Mazury.Holiday", title: "Welcome to", titleHighlight: "Great Lakes", p1: "Discover the magic of Masuria from our luxury apartments.", p2: "Whether you seek peace in Giżycko or luxury in Fuleda." },
        apartments: { title: "Our Apartments", description: "Choose the perfect place for your rest.", details: "Details", pricePrefix: "from", night: "night", people: "people", items: { stranda: { title: "Stranda Apartments", location: "Giżycko", description: "Comfortable apartments in the heart of Stranda port." }, kisajno: { title: "Kisajno Apartments", location: "Giżycko", description: "Luxury on the shores of Lake Kisajno." }, fuleda: { title: "Fuleda Apartments", location: "Fuleda", description: "An oasis of peace away from the city." } } },
        charter: { tag: "No license", title: "Motor Yacht Charter", description: "Stillo 30 motor yacht available without a license.", model: "Stillo 30 (2020)", cabins: "3 Cabins", checkBtn: "Check availability", premiumFleet: "Premium Fleet", feature1: "No license", feature2: "Year 2020", feature3: "Luxury equipment", detailsBtn: "Details" },
        stranda: { subtitle: "Luxury by Lake Kisajno", description: "Stranda Residence combines modern design with nature.", building: "Building", apartment: "Apartment" },
        details: { about: "About", amenities: "Amenities", booking: "Booking", checkAvailability: "Check availability and book.", callBtn: "Call", lowPrice: "Best price guarantee.", descriptionPart1: "Luxury apartment in building", descriptionPart2: "at Stranda Residence.", descriptionPart3: "Unforgettable views of Lake Kisajno.", items: { view: "Lake view", ac: "A/C", terrace: "Terrace", kitchen: "Kitchenette", tv: "Smart TV", wifi: "WiFi", parking: "Parking", sauna: "Sauna access" } },
        footer: { brandDesc: "Unique moments in Masuria.", navTitle: "Navigation", contactTitle: "Contact", followTitle: "Follow", rights: "All rights reserved.", linksTitle: "Links" }
    },
    de: {
        nav: { about: "Über uns", apartments: "Apartments", cottages: "Hütten", charter: "Charter", port: "Hafen", attractions: "Attraktionen", cooperation: "Zusammenarbeit", contact: "Kontakt", rooms: "Zimmer", bookBtn: "Buchen" },
        hero: { title: "Urlaub in Masuren", subtitle: "ABENTEUER ERLEBEN", apartmentsBtn: "Unsere Apartments", charterBtn: "Yachtcharter" },
        intro: { tag: "Mazury.Holiday", title: "Willkommen in", titleHighlight: "Masuren", p1: "Entdecken Sie die Magie Masurens.", p2: "Ob Ruhe in Giżycko oder Luxus in Fuleda." },
        apartments: { title: "Unsere Apartments", description: "Wählen Sie den perfekten Ort.", details: "Details", pricePrefix: "ab", night: "Nacht", people: "Pers.", items: { stranda: { title: "Stranda Apartments", location: "Giżycko", description: "Komfort im Herzen von Stranda." }, kisajno: { title: "Kisajno Apartments", location: "Giżycko", description: "Luxus am Kisajno-See." }, fuleda: { title: "Fuleda Apartments", location: "Fuleda", description: "Ruheoase in der Natur." } } },
        charter: { tag: "Führerscheinfrei", title: "Motoryachtcharter", description: "Stillo 30 ohne Führerschein.", model: "Stillo 30 (2020)", cabins: "3 Kabinen", checkBtn: "Verfügbarkeit", premiumFleet: "Premium", feature1: "Kein Schein", feature2: "Baujahr 2020", feature3: "Luxus", detailsBtn: "Details" },
        stranda: { subtitle: "Luxus am Kisajno", description: "Stranda Residence verbindet Design mit Natur.", building: "Gebäude", apartment: "Apartment" },
        details: { about: "Über", amenities: "Ausstattung", booking: "Buchung", checkAvailability: "Verfügbarkeit prüfen.", callBtn: "Anrufen", lowPrice: "Bestpreisgarantie.", descriptionPart1: "Luxusapartment im Gebäude", descriptionPart2: "in Stranda Residence.", descriptionPart3: "Unvergesslicher Seeblick.", items: { view: "Seeblick", ac: "Klimaanlage", terrace: "Terrasse", kitchen: "Küche", tv: "Smart TV", wifi: "WLAN", parking: "Parkplatz", sauna: "Sauna" } },
        footer: { brandDesc: "Einzigartige Momente.", navTitle: "Navigation", contactTitle: "Kontakt", followTitle: "Folgen", rights: "Rechte vorbehalten.", linksTitle: "Links" }
    },
    es: {
        nav: { about: "Nosotros", apartments: "Apartamentos", cottages: "Cabañas", charter: "Chárter", port: "Puerto", attractions: "Atracciones", cooperation: "Cooperación", contact: "Contacto", rooms: "Habitaciones", bookBtn: "Reservar" },
        hero: { title: "Vacaciones en Masuria", subtitle: "MOMENTOS ÚNICOS", apartmentsBtn: "Nuestros Apartamentos", charterBtn: "Alquiler de Yates" },
        intro: { tag: "Mazury.Holiday", title: "Bienvenido a", titleHighlight: "Grandes Lagos", p1: "Descubra la magia de Masuria.", p2: "Ya sea descanso en Giżycko o lujo en Fuleda." },
        apartments: { title: "Nuestros Apartamentos", description: "Elija el lugar perfecto.", details: "Detalles", pricePrefix: "desde", night: "noche", people: "pers.", items: { stranda: { title: "Apartamentos Stranda", location: "Giżycko", description: "Confort en el puerto Stranda." }, kisajno: { title: "Apartamentos Kisajno", location: "Giżycko", description: "Lujo en el lago Kisajno." }, fuleda: { title: "Apartamentos Fuleda", location: "Fuleda", description: "Oasis de paz." } } },
        charter: { tag: "Sin licencia", title: "Alquiler de Yates", description: "Yate Stillo 30 sin licencia.", model: "Stillo 30 (2020)", cabins: "3 Cabinas", checkBtn: "Disponibilidad", premiumFleet: "Premium", feature1: "Sin licencia", feature2: "2020", feature3: "Lujo", detailsBtn: "Detalles" },
        stranda: { subtitle: "Lujo en Lago Kisajno", description: "Diseño moderno y naturaleza.", building: "Edificio", apartment: "Apartamento" },
        details: { about: "Sobre", amenities: "Comodidades", booking: "Reserva", checkAvailability: "Verificar disponibilidad.", callBtn: "Llamar", lowPrice: "Mejor precio.", descriptionPart1: "Apartamento de lujo en", descriptionPart2: "Stranda Residence.", descriptionPart3: "Vistas inolvidables.", items: { view: "Vistas al lago", ac: "Aire acond.", terrace: "Terraza", kitchen: "Cocina", tv: "Smart TV", wifi: "WiFi", parking: "Parking", sauna: "Sauna" } },
        footer: { brandDesc: "Momentos únicos.", navTitle: "Navegación", contactTitle: "Contacto", followTitle: "Síguenos", rights: "Reservados todos los derechos.", linksTitle: "Enlaces" }
    },
    it: {
        nav: { about: "Chi siamo", apartments: "Appartamenti", cottages: "Case", charter: "Noleggio", port: "Porto", attractions: "Attrazioni", cooperation: "Cooperazione", contact: "Contatti", rooms: "Camere", bookBtn: "Prenota" },
        hero: { title: "Vacanze in Masuria", subtitle: "MOMENTI UNICI", apartmentsBtn: "I nostri appartamenti", charterBtn: "Noleggio Yacht" },
        intro: { tag: "Mazury.Holiday", title: "Benvenuti nei", titleHighlight: "Grandi Laghi", p1: "Scopri la magia della Masuria.", p2: "Relax a Giżycko o lusso a Fuleda." },
        apartments: { title: "Appartamenti", description: "Scegli il posto perfetto.", details: "Dettagli", pricePrefix: "da", night: "notte", people: "pers.", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Comfort al porto." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Lusso sul lago." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Oasi di pace." } } },
        charter: { tag: "Senza patente", title: "Noleggio Yacht", description: "Stillo 30 senza patente.", model: "Stillo 30 (2020)", cabins: "3 Cabine", checkBtn: "Disponibilità", premiumFleet: "Premium", feature1: "No patente", feature2: "2020", feature3: "Lusso", detailsBtn: "Dettagli" },
        stranda: { subtitle: "Lusso sul lago", description: "Design moderno e natura.", building: "Edificio", apartment: "Appartamento" },
        details: { about: "Info", amenities: "Servizi", booking: "Prenotazione", checkAvailability: "Controlla disponibilità.", callBtn: "Chiama", lowPrice: "Miglior prezzo.", descriptionPart1: "Appartamento di lusso in", descriptionPart2: "Stranda Residence.", descriptionPart3: "Vista indimenticabile.", items: { view: "Vista lago", ac: "Aria cond.", terrace: "Terrazza", kitchen: "Cucina", tv: "Smart TV", wifi: "WiFi", parking: "Parcheggio", sauna: "Sauna" } },
        footer: { brandDesc: "Momenti unici.", navTitle: "Navigazione", contactTitle: "Contatti", followTitle: "Seguici", rights: "Tutti i diritti riservati.", linksTitle: "Link" }
    },
    fr: {
        nav: { about: "À propos", apartments: "Appartements", cottages: "Chalets", charter: "Location", port: "Port", attractions: "Attractions", cooperation: "Coopération", contact: "Contact", rooms: "Chambres", bookBtn: "Réserver" },
        hero: { title: "Vacances en Mazurie", subtitle: "MOMENTS UNIQUES", apartmentsBtn: "Nos Appartements", charterBtn: "Location de Yacht" },
        intro: { tag: "Mazury.Holiday", title: "Bienvenue aux", titleHighlight: "Grands Lacs", p1: "Découvrez la magie de la Mazurie.", p2: "Repos à Giżycko ou luxe à Fuleda." },
        apartments: { title: "Nos Appartements", description: "Choisissez l'endroit idéal.", details: "Détails", pricePrefix: "dès", night: "nuit", people: "pers.", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Confort au port." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Luxe sur le lac." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Oasis de paix." } } },
        charter: { tag: "Sans permis", title: "Location Yacht", description: "Stillo 30 sans permis.", model: "Stillo 30 (2020)", cabins: "3 Cabines", checkBtn: "Disponibilité", premiumFleet: "Premium", feature1: "Sans permis", feature2: "2020", feature3: "Luxe", detailsBtn: "Détails" },
        stranda: { subtitle: "Luxe sur le lac", description: "Design moderne et nature.", building: "Bâtiment", apartment: "Appartement" },
        details: { about: "À propos", amenities: "Équipements", booking: "Réservation", checkAvailability: "Vérifier dispo.", callBtn: "Appeler", lowPrice: "Meilleur prix.", descriptionPart1: "Appartement de luxe", descriptionPart2: "à Stranda.", descriptionPart3: "Vue inoubliable.", items: { view: "Vue lac", ac: "Clim", terrace: "Terrasse", kitchen: "Cuisine", tv: "Smart TV", wifi: "WiFi", parking: "Parking", sauna: "Sauna" } },
        footer: { brandDesc: "Moments uniques.", navTitle: "Navigation", contactTitle: "Contact", followTitle: "Suivez-nous", rights: "Tous droits réservés.", linksTitle: "Liens" }
    },
    cs: {
        nav: { about: "O nás", apartments: "Apartmány", cottages: "Chaty", charter: "Pronájem", port: "Přístav", attractions: "Atrakce", cooperation: "Spolupráce", contact: "Kontakt", rooms: "Pokoje", bookBtn: "Rezervovat" },
        hero: { title: "Dovolená na Mazurech", subtitle: "JEDINEČNÉ OKAMŽIKY", apartmentsBtn: "Naše Apartmány", charterBtn: "Jachty" },
        intro: { tag: "Mazury.Holiday", title: "Vítejte na", titleHighlight: "Mazurech", p1: "Objevte kouzlo Mazur.", p2: "Odpočinek v Giżycku." },
        apartments: { title: "Naše Apartmány", description: "Vyberte si místo.", details: "Podrobnosti", pricePrefix: "od", night: "noc", people: "os.", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Komfort v přístavu." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Luxus u jezera." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Oáza klidu." } } },
        charter: { tag: "Bez průkazu", title: "Pronájem Jachty", description: "Stillo 30 bez průkazu.", model: "Stillo 30 (2020)", cabins: "3 Kabiny", checkBtn: "Dostupnost", premiumFleet: "Premium", feature1: "Bez průkazu", feature2: "2020", feature3: "Luxus", detailsBtn: "Detaily" },
        stranda: { subtitle: "Luxus u jezera", description: "Moderní design.", building: "Budova", apartment: "Apartmán" },
        details: { about: "O apartmánu", amenities: "Vybavení", booking: "Rezervace", checkAvailability: "Ovĕřit dostupnost.", callBtn: "Zavolat", lowPrice: "Nejlepší cena.", descriptionPart1: "Luxusní apartmán v", descriptionPart2: "Stranda Residence.", descriptionPart3: "Výhled na jezero.", items: { view: "Výhled", ac: "Klima", terrace: "Terasa", kitchen: "Kuchyně", tv: "TV", wifi: "WiFi", parking: "Parkování", sauna: "Sauna" } },
        footer: { brandDesc: "Jedinečné chvíle.", navTitle: "Navigace", contactTitle: "Kontakt", followTitle: "Sledujte", rights: "Všechna práva vyhrazena.", linksTitle: "Odkazy" }
    },
    lt: {
        nav: { about: "Apie mus", apartments: "Apartamentai", cottages: "Namelliai", charter: "Nuoma", port: "Uostas", attractions: "Atrakcijos", cooperation: "Bendradarbiavimas", contact: "Kontaktai", rooms: "Kambariai", bookBtn: "Rezervuoti" },
        hero: { title: "Atostogos Mozūrijoje", subtitle: "YPATINGOS AKIMIRKOS", apartmentsBtn: "Mūsų Apartamentai", charterBtn: "Jachtų Nuoma" },
        intro: { tag: "Mazury.Holiday", title: "Sveiki atvykę", titleHighlight: "Didieji Ežerai", p1: "Atraskite Mozūrijos magiją.", p2: "Poilsis Giżycko." },
        apartments: { title: "Mūsų Apartamentai", description: "Pasirinkite vietą.", details: "Detalės", pricePrefix: "nuo", night: "naktis", people: "žm.", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Komfortas uoste." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Prabanga." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Ramybės oazė." } } },
        charter: { tag: "Be licencijos", title: "Jachtos Nuoma", description: "Stillo 30 be licencijos.", model: "Stillo 30 (2020)", cabins: "3 Kajutės", checkBtn: "Tikrinti", premiumFleet: "Premium", feature1: "Be licencijos", feature2: "2020", feature3: "Prabanga", detailsBtn: "Detalės" },
        stranda: { subtitle: "Prabanga prie ežero", description: "Modernus dizainas.", building: "Pastatas", apartment: "Apartamentas" },
        details: { about: "Apie", amenities: "Patogumai", booking: "Rezervacija", checkAvailability: "Tikrinti.", callBtn: "Skambinti", lowPrice: "Geriausia kaina.", descriptionPart1: "Prabangūs apartamentai", descriptionPart2: "Stranda.", descriptionPart3: "Ežero vaizdas.", items: { view: "Vaizdas", ac: "Kondicionierius", terrace: "Terasa", kitchen: "Virtuvė", tv: "TV", wifi: "WiFi", parking: "Parkingas", sauna: "Pirtis" } },
        footer: { brandDesc: "Ypatingos akimirkos.", navTitle: "Navigacija", contactTitle: "Kontaktai", followTitle: "Sekite", rights: "Visos teisės saugomos.", linksTitle: "Nuorodos" }
    },
    dk: {
        nav: { about: "Om os", apartments: "Lejligheder", cottages: "Hytter", charter: "Charter", port: "Havn", attractions: "Attraktioner", cooperation: "Samarbejde", contact: "Kontakt", rooms: "Værelser", bookBtn: "Book nu" },
        hero: { title: "Ferie i Masurien", subtitle: "UNIKKE ØJEBLIKKE", apartmentsBtn: "Lejligheder", charterBtn: "Yachtcharter" },
        intro: { tag: "Mazury.Holiday", title: "Velkommen til", titleHighlight: "De Store Søer", p1: "Oplev magien.", p2: "Hvile i Giżycko." },
        apartments: { title: "Lejligheder", description: "Vælg det perfekte sted.", details: "Detaljer", pricePrefix: "fra", night: "nat", people: "pers.", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Komfort." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Luksus." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Oase." } } },
        charter: { tag: "Uden certifikat", title: "Leje af Yacht", description: "Stillo 30.", model: "Stillo 30", cabins: "3 Kahytter", checkBtn: "Tjek", premiumFleet: "Premium", feature1: "Ingen licens", feature2: "2020", feature3: "Luksus", detailsBtn: "Se detaljer" },
        stranda: { subtitle: "Luksus ved søen", description: "Moderne design.", building: "Bygning", apartment: "Lejlighed" },
        details: { about: "Om", amenities: "Faciliteter", booking: "Booking", checkAvailability: "Tjek ledighed.", callBtn: "Ring", lowPrice: "Bedste pris.", descriptionPart1: "Luksus lejlighed", descriptionPart2: "i Stranda.", descriptionPart3: "Søudsigt.", items: { view: "Søudsigt", ac: "Aircon", terrace: "Terrasse", kitchen: "Køkken", tv: "TV", wifi: "WiFi", parking: "Parkering", sauna: "Sauna" } },
        footer: { brandDesc: "Unikke øjeblikke.", navTitle: "Navigation", contactTitle: "Kontakt", followTitle: "Følg os", rights: "Alle rettigheder forbeholdes.", linksTitle: "Links" }
    },
    // Minimal placeholders for others to ensure structure (programmatic copy would be safer but user wants specific)
    se: {
        nav: { about: "Om oss", apartments: "Lägenheter", cottages: "Stugor", charter: "Charter", port: "Hamn", attractions: "Sevärdheter", cooperation: "Samarbete", contact: "Kontakt", rooms: "Rum", bookBtn: "Boka" },
        hero: { title: "Semester i Masurien", subtitle: "UNIKA STUNDER", apartmentsBtn: "Lägenheter", charterBtn: "Yacht" },
        intro: { tag: "Mazury.Holiday", title: "Välkommen", titleHighlight: "Sjöarna", p1: "Upptäck magin.", p2: "Avkoppling." },
        apartments: { title: "Våra Lägenheter", description: "Välj plats.", details: "Detaljer", pricePrefix: "från", night: "natt", people: "pers", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Komfort." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Lyx." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Oas." } } },
        charter: { tag: "Utan licens", title: "Båtcharter", description: "Stillo 30.", model: "Stillo 30", cabins: "3 Hytter", checkBtn: "Kolla", premiumFleet: "Premium", feature1: "Ingen licens", feature2: "2020", feature3: "Lyx", detailsBtn: "Detaljer" },
        stranda: { subtitle: "Lyx vid sjön", description: "Modern design.", building: "Byggnad", apartment: "Lägenhet" },
        details: { about: "Om", amenities: "Bekvämligheter", booking: "Bokning", checkAvailability: "Kolla ledighet.", callBtn: "Ring", lowPrice: "Bästa pris.", descriptionPart1: "Lyxlägenhet", descriptionPart2: "Stranda.", descriptionPart3: "Sjöutsikt.", items: { view: "Sjöutsikt", ac: "AC", terrace: "Terrass", kitchen: "Kök", tv: "TV", wifi: "WiFi", parking: "Parkering", sauna: "Bastu" } },
        footer: { brandDesc: "Unika stunder.", navTitle: "Navigering", contactTitle: "Kontakt", followTitle: "Följ", rights: "Alla rättigheter.", linksTitle: "Länkar" }
    },
    no: {
        nav: { about: "Om oss", apartments: "Leiligheter", cottages: "Hytter", charter: "Charter", port: "Havn", attractions: "Attraksjoner", cooperation: "Samarbeid", contact: "Kontakt", rooms: "Rom", bookBtn: "Bestill" },
        hero: { title: "Ferie i Masuria", subtitle: "UNIKE ØYEBLIKK", apartmentsBtn: "Leiligheter", charterBtn: "Yacht" },
        intro: { tag: "Mazury.Holiday", title: "Velkommen", titleHighlight: "Innsjøene", p1: "Oppdag magien.", p2: "Avslapning." },
        apartments: { title: "Våre Leiligheter", description: "Velg sted.", details: "Detaljer", pricePrefix: "fra", night: "natt", people: "pers", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Komfort." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Luksus." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Oase." } } },
        charter: { tag: "Uten lisens", title: "Båtutleie", description: "Stillo 30.", model: "Stillo 30", cabins: "3 Lugarer", checkBtn: "Sjekk", premiumFleet: "Premium", feature1: "Ingen lisens", feature2: "2020", feature3: "Luksus", detailsBtn: "Detaljer" },
        stranda: { subtitle: "Luksus", description: "Moderne.", building: "Bygning", apartment: "Leilighet" },
        details: { about: "Om", amenities: "Fasiliteter", booking: "Bestilling", checkAvailability: "Sjekk.", callBtn: "Ring", lowPrice: "Best pris.", descriptionPart1: "Luksus", descriptionPart2: "Stranda.", descriptionPart3: "Utsikt.", items: { view: "Utsikt", ac: "AC", terrace: "Terrasse", kitchen: "Kjøkken", tv: "TV", wifi: "WiFi", parking: "Parkering", sauna: "Badstue" } },
        footer: { brandDesc: "Unike øyeblikk.", navTitle: "Navigasjon", contactTitle: "Kontakt", followTitle: "Følg", rights: "Alle rettigheter.", linksTitle: "Lenker" }
    },
    fi: {
        nav: { about: "Meistä", apartments: "Huoneistot", cottages: "Mökit", charter: "Vuokraus", port: "Satama", attractions: "Nähtävyydet", cooperation: "Yhteistyö", contact: "Yhteystiedot", rooms: "Huoneet", bookBtn: "Varaa" },
        hero: { title: "Loma", subtitle: "AINUTLAATUINEN", apartmentsBtn: "Huoneistot", charterBtn: "Venevuokraus" },
        intro: { tag: "Mazury.Holiday", title: "Tervetuloa", titleHighlight: "Järvet", p1: "Koe taika.", p2: "Lepo." },
        apartments: { title: "Huoneistot", description: "Valitse.", details: "Tiedot", pricePrefix: "alk.", night: "yö", people: "hlö", items: { stranda: { title: "Stranda", location: "Giżycko", description: "Mukavuus." }, kisajno: { title: "Kisajno", location: "Giżycko", description: "Luksus." }, fuleda: { title: "Fuleda", location: "Fuleda", description: "Rauha." } } },
        charter: { tag: "Ilman lupaa", title: "Venevuokraus", description: "Stillo 30.", model: "Stillo 30", cabins: "3 Hyttiä", checkBtn: "Tarkista", premiumFleet: "Premium", feature1: "Ei lupaa", feature2: "2020", feature3: "Luksus", detailsBtn: "Tiedot" },
        stranda: { subtitle: "Luksus", description: "Moderni.", building: "Rakennus", apartment: "Huoneisto" },
        details: { about: "Tietoa", amenities: "Varusteet", booking: "Varaus", checkAvailability: "Tarkista.", callBtn: "Soita", lowPrice: "Paras hinta.", descriptionPart1: "Luksus", descriptionPart2: "Stranda.", descriptionPart3: "Näkymä.", items: { view: "Näkymä", ac: "Ilmastointi", terrace: "Terassi", kitchen: "Keittiö", tv: "TV", wifi: "WiFi", parking: "Pysäköinti", sauna: "Sauna" } },
        footer: { brandDesc: "Ainutlaatuista.", navTitle: "Navigaatio", contactTitle: "Yhteystiedot", followTitle: "Seuraa", rights: "Kaikki oikeudet.", linksTitle: "Linkit" }
    }
};

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.pl;
